ovgu-ubit/output

output-api/src/main.ts
=> Revert "41 swagger base path"

output-api/src/services/entities/publication-type.service.ts, output-api/src/services/import/base-import.service.ts, output-api/src/services/init.service.ts, output-ui/src/app/tools/select-institute-dialog/select-institute-dialog.component.ts
=> 53 publicationtype align to kdsf

output-api/src/services/entities/institution.service.ts, output-api/src/services/entities/publication.service.ts, output-interfaces/Config.ts, output-ui/src/app/interfaces/table.ts, output-ui/src/app/pages/authors/authors.component.ts, output-ui/src/app/pages/master-data/contracts/contracts.component.ts, output-ui/src/app/pages/master-data/funders/funders.component.ts, output-ui/src/app/pages/master-data/greater-entities/greater-entities.component.ts, output-ui/src/app/pages/master-data/institutions/institutions.component.ts, output-ui/src/app/pages/master-data/oa-categories/oa-categories.component.ts, output-ui/src/app/pages/master-data/pub-types/pub-types.component.ts, output-ui/src/app/pages/master-data/publishers/publishers.component.ts, output-ui/src/app/services/entities/publication.service.ts, output-ui/src/app/tools/select-institute-dialog/select-institute-dialog.component.ts
=> 78 publicationfilter from other indextables are not working

output-api/output-server-prod.config.js, output-ui/src/app/pages/windows/publication-form/publication-form.component.html, output-ui/src/app/pages/windows/publication-form/publication-form.component.ts
=> 107 publicationform always unsaved changes

output-api/package.json, output-api/src/main.ts, output-ui/src/app/app.component.ts, output-ui/src/app/pages/windows/contract-form/contract-form.component.ts, output-ui/src/app/pages/windows/greater-entity-form/greater-entity-form.component.ts
=> 110 contractform identifier cannot be created for new contract

output-api/package.json, output-api/src/controller/AuthorController.ts, output-api/src/entity/Author.ts, output-api/src/main.ts, output-api/src/services/database.config.service.ts, output-api/src/services/entities/author.service.ts, output-api/src/services/entities/contract.service.ts, output-api/src/services/entities/funder.service.ts, output-api/src/services/entities/greater-entitiy.service.ts, output-api/src/services/entities/institution.service.ts, output-api/src/services/entities/invoice.service.ts, output-api/src/services/entities/language.service.ts, output-api/src/services/entities/oa-category.service.ts, output-api/src/services/entities/publication-type.service.ts, output-api/src/services/entities/publication.service.ts, output-api/src/services/entities/publisher.service.ts, output-ui/src/app/app.component.ts, output-ui/src/app/pages/authors/authors.component.ts, output-ui/src/app/pages/master-data/contracts/contracts.component.ts, output-ui/src/app/pages/master-data/cost-center/cost-center.component.ts, output-ui/src/app/pages/master-data/cost-types/cost-types.component.ts, output-ui/src/app/pages/master-data/funders/funders.component.ts, output-ui/src/app/pages/master-data/greater-entities/greater-entities.component.ts, output-ui/src/app/pages/master-data/institutions/institutions.component.ts, output-ui/src/app/pages/master-data/oa-categories/oa-categories.component.ts, output-ui/src/app/pages/master-data/pub-types/pub-types.component.ts, output-ui/src/app/pages/master-data/publishers/publishers.component.ts, output-ui/src/app/pages/publications/publications.component.ts
=> 124 entity too large

output-api/src/services/import/abstract-import.ts, output-api/src/services/import/open-access-monitor-enrich.service.ts, output-api/src/services/import/open-access-monitor-import.service.ts, output-api/src/services/statistics.service.ts, output-ui/src/app/pages/statistics/statistics-year/statistics-year.component.ts, output-ui/src/app/pages/statistics/statistics.component.ts, output-ui/src/app/tools/alias-form/alias-form.component.html, output-ui/src/app/tools/select-institute-dialog/select-institute-dialog.component.ts
=> 130 oam import pub date not correctly imported

output-api/src/services/entities/greater-entitiy.service.ts, output-ui/src/app/pages/windows/publication-form/publication-form.component.html, output-ui/src/app/pages/windows/publication-form/publication-form.component.ts
=> 128-greateentityidentifiers

output-api/src/controller/ExportController.ts, output-api/src/services/import/doaj-enrich.service.ts
=> 176 doaj enrich bug

output-api/src/services/entities/contract.service.ts, output-api/src/services/entities/funder.service.ts, output-api/src/services/entities/greater-entitiy.service.ts, output-api/src/services/entities/oa-category.service.ts, output-api/src/services/entities/publication-type.service.ts, output-api/src/services/entities/publisher.service.ts
=> withDeleted pubs to also process soft deletes

output-api/config.ts.template, output-api/src/services/entities/contract.service.ts, output-api/src/services/entities/institution.service.ts, output-api/src/services/export/author-export.service.ts, output-api/src/services/export/contract-export.service.ts, output-api/src/services/export/cost-center-export.service.ts, output-api/src/services/export/cost-type-export.service.ts, output-api/src/services/export/funder-export.service.ts, output-api/src/services/export/greater-entity-export.service.ts, output-api/src/services/export/institute-export.service.ts, output-api/src/services/export/oa-cat-export.service.ts, output-api/src/services/export/pub-type-export.service.ts, output-api/src/services/export/publisher-export.service.ts, output-interfaces/Publication.ts, output-ui/src/app/pages/statistics/statistics.component.html, output-ui/src/app/pages/statistics/statistics.component.ts
=> 197 export master data

output-api/src/services/statistics.service.ts, output-interfaces/Statistics.ts, output-ui/src/app/pages/statistics/statistics-year/statistics-year.component.html, output-ui/src/app/pages/statistics/statistics-year/statistics-year.component.ts
=> 193 statistics chiplist of filters

output-ui/src/app/pages/windows/publication-form/publication-form.component.css, output-ui/src/app/pages/windows/publication-form/publication-form.component.html
=> removed color from status

output-api/src/services/entities/publication.service.ts, output-ui/src/app/pages/windows/invoice-form/invoice-form.component.html, output-ui/src/app/pages/windows/invoice-form/invoice-form.component.ts
=> invoice cost center bug

output-api/src/app.module.ts, output-api/src/controller/StatusController.ts, output-api/src/entity/Status.ts, output-api/src/init.module.ts, output-api/src/services/entities/status.service.ts, output-interfaces/Publication.ts, output-ui/src/app/app-routing.module.ts, output-ui/src/app/app.component.html, output-ui/src/app/app.module.ts, output-ui/src/app/pages/master-data/statuses/statuses.component.html, output-ui/src/app/pages/master-data/statuses/statuses.component.spec.ts, output-ui/src/app/pages/master-data/statuses/statuses.component.ts, output-ui/src/app/pages/windows/publication-form/publication-form.component.html, output-ui/src/app/pages/windows/publication-form/publication-form.component.ts, output-ui/src/app/pages/windows/role-form/role-form.component.ts, output-ui/src/app/pages/windows/status-form/status-form.component.html, output-ui/src/app/pages/windows/status-form/status-form.component.spec.ts, output-ui/src/app/pages/windows/status-form/status-form.component.ts, output-ui/src/app/services/entities/status.service.ts
=> 211 status add configurable description

output-ui/src/app/pages/publications/publications.component.ts
=> number fix

output-api/src/services/entities/publication.service.ts, output-api/src/services/import/abstract-import.ts, output-api/src/services/statistics.service.ts, output-ui/src/app/pages/statistics/statistics-year/statistics-year.component.ts
=> 241 statistics show eur for cost statistics

output-api/src/services/import/abstract-import.ts
=> import invoice error

output-api/src/services/filter/missing-inst-author-filter.service.ts
=> fixed typo

output-api/src/services/entities/author.service.ts, output-api/src/services/entities/contract.service.ts, output-api/src/services/entities/funder.service.ts, output-api/src/services/entities/greater-entitiy.service.ts, output-api/src/services/entities/institution.service.ts, output-api/src/services/entities/oa-category.service.ts, output-api/src/services/entities/publication-type.service.ts, output-api/src/services/entities/publication.service.ts, output-api/src/services/entities/publisher.service.ts, output-ui/src/app/pages/publications/publications.component.html, output-ui/src/app/pages/publications/publications.component.ts, output-ui/src/app/tools/filter-view/filter-view.component.ts, output-ui/src/app/tools/table/table.component.html, output-ui/src/app/tools/table/table.component.ts
=> 290 publications simple filters are not saved in state

output-api/src/app.module.ts, output-api/src/controller/ContractController.ts, output-api/src/controller/GreaterEntityController.ts, output-api/src/services/entities/contract.service.ts, output-api/src/services/entities/greater-entitiy.service.ts, output-api/src/services/entities/publication.service.ts, output-api/src/services/import/abstract-import.ts
=> 309 greaterentitity cascade not working to identifiers

output-api/src/services/entities/author.service.ts, output-ui/src/app/pages/windows/author-form/author-form.component.ts, output-ui/src/app/pages/windows/publication-form/publication-form.component.ts, output-ui/src/app/tools/select-entity/select-entity.component.html, output-ui/src/app/tools/select-entity/select-entity.component.ts
closes #331 
closes #332 
closes #333 
closes #326
=> 330 delete author not possible when aliases are existing

output-ui/src/app/pages/windows/invoice-form/invoice-form.component.html, output-ui/src/app/pages/windows/reporting-year-form/reporting-year-form.component.html, output-ui/src/app/services/entities/publication.service.ts, output-ui/src/app/tools/table/table.component.ts
=> 351 change reporting year not possible
